// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Models.Migrations
{
    [DbContext(typeof(NutritionContext))]
    [Migration("20181018034901_Nutrition_Migration_1")]
    partial class Nutrition_Migration_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Models.NutritionContext+FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<decimal>("Cholesterol");

                    b.Property<decimal>("DietaryFiber");

                    b.Property<decimal>("InsolubleFiber");

                    b.Property<string>("Name");

                    b.Property<decimal>("Protein");

                    b.Property<decimal>("SaturatedFat");

                    b.Property<decimal>("ServingSize");

                    b.Property<string>("ServingUnit");

                    b.Property<decimal>("Sodium");

                    b.Property<decimal>("SolubleFiber");

                    b.Property<decimal>("Sugar");

                    b.Property<decimal>("TotalCarbs");

                    b.Property<decimal>("TotalFat");

                    b.Property<decimal>("TransFat");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("Models.NutritionContext+Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Servings");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Models.NutritionContext+RecipeLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FoodItemId");

                    b.Property<decimal>("Quantity");

                    b.Property<string>("QuantityUnit");

                    b.Property<int?>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeLines");
                });

            modelBuilder.Entity("Models.NutritionContext+RecipeLine", b =>
                {
                    b.HasOne("Models.NutritionContext+FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId");

                    b.HasOne("Models.NutritionContext+Recipe")
                        .WithMany("RecipeLines")
                        .HasForeignKey("RecipeId");
                });
#pragma warning restore 612, 618
        }
    }
}
